server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
# 企查查
qichacha:
  appkey: 282c1901c0b8711ea89b97cd30aeb1e8c3
  seckey: 2E569IGHQYAAADQ7M5LBKIL4K9ADRDDEO3
  apiurl: https://pro.qichacha.com/api/yj/ECIMatch/CompanyVerify

user:
  password: 123456

jodconverter:
  enabled: true
  # open office 安装路径
  office-home: C:\Program Files (x86)\OpenOffice 4

  max-tasks-per-process: 10
  port-numbers: 8100
  kill-existing-process: true
